// <auto-generated />
using System;
using Cheetah_DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CheetahDataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230130192510_AddToDB2")]
    partial class AddToDB2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cheetah_DataAccess.CopyProduct", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idRole")
                        .HasColumnType("int");

                    b.HasKey("ProductID");

                    b.HasIndex("idRole");

                    b.ToTable("CopyProducts");
                });

            modelBuilder.Entity("Cheetah_DataAccess.CopyROLE", b =>
                {
                    b.Property<int>("idRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idRole"));

                    b.Property<Guid>("guidRole")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("roleName")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)");

                    b.HasKey("idRole");

                    b.ToTable("CopyROLEs");
                });

            modelBuilder.Entity("Cheetah_DataAccess.Parameters.P_ParameterList", b =>
                {
                    b.Property<long>("IdRecord")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdRecord"));

                    b.Property<long>("CreateTimeRecord")
                        .HasColumnType("bigint");

                    b.Property<bool>("DsblRecord")
                        .HasColumnType("bit");

                    b.Property<Guid>("GuidRecord")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("LastUpdatedRecord")
                        .HasColumnType("bigint");

                    b.Property<long>("PCode")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("PCost")
                        .HasColumnType("numeric");

                    b.Property<string>("PDescription")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<long?>("PERPCode")
                        .HasColumnType("bigint");

                    b.Property<long>("PIndex")
                        .HasColumnType("bigint");

                    b.Property<string>("PName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdRecord");

                    b.ToTable("P_ParameterList");
                });

            modelBuilder.Entity("Cheetah_DataAccess.Parameters.P_ParameterType", b =>
                {
                    b.Property<long>("IdRecord")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdRecord"));

                    b.Property<long>("CreateTimeRecord")
                        .HasColumnType("bigint");

                    b.Property<bool>("DsblRecord")
                        .HasColumnType("bit");

                    b.Property<Guid>("GuidRecord")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("LastUpdatedRecord")
                        .HasColumnType("bigint");

                    b.Property<long>("PCode")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("PCost")
                        .HasColumnType("numeric");

                    b.Property<string>("PDescription")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<long?>("PERPCode")
                        .HasColumnType("bigint");

                    b.Property<long>("PIndex")
                        .HasColumnType("bigint");

                    b.Property<string>("PName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("P_ParameterListIdRecord")
                        .HasColumnType("bigint");

                    b.HasKey("IdRecord");

                    b.HasIndex("P_ParameterListIdRecord");

                    b.ToTable("P_ParameterType");
                });

            modelBuilder.Entity("Cheetah_DataAccess.CopyProduct", b =>
                {
                    b.HasOne("Cheetah_DataAccess.CopyROLE", "copyROLE")
                        .WithMany()
                        .HasForeignKey("idRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("copyROLE");
                });

            modelBuilder.Entity("Cheetah_DataAccess.Parameters.P_ParameterType", b =>
                {
                    b.HasOne("Cheetah_DataAccess.Parameters.P_ParameterList", null)
                        .WithMany("PL_ParameterType")
                        .HasForeignKey("P_ParameterListIdRecord");
                });

            modelBuilder.Entity("Cheetah_DataAccess.Parameters.P_ParameterList", b =>
                {
                    b.Navigation("PL_ParameterType");
                });
#pragma warning restore 612, 618
        }
    }
}
