// <auto-generated />
using System;
using Cheetah_DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CheetahDataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230130193217_AddToDB3")]
    partial class AddToDB3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cheetah_DataAccess.CopyProduct", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idRole")
                        .HasColumnType("int");

                    b.HasKey("ProductID");

                    b.HasIndex("idRole");

                    b.ToTable("CopyProducts");
                });

            modelBuilder.Entity("Cheetah_DataAccess.CopyROLE", b =>
                {
                    b.Property<int>("idRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idRole"));

                    b.Property<Guid>("guidRole")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("roleName")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)");

                    b.HasKey("idRole");

                    b.ToTable("CopyROLEs");
                });

            modelBuilder.Entity("Cheetah_DataAccess.Masters.M_Approve", b =>
                {
                    b.Property<long>("IdRecord")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdRecord"));

                    b.Property<byte?>("APV_Attachment")
                        .HasColumnType("tinyint");

                    b.Property<string>("APV_Number")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("APV_Subject")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("APV_TaskRecieveDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("APV_TaskSentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("APV_UserDescription")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<long?>("APV_idRequestInformation")
                        .HasColumnType("bigint");

                    b.Property<long?>("APV_idUserAction")
                        .HasColumnType("bigint");

                    b.Property<long?>("APV_idUserInCharge")
                        .HasColumnType("bigint");

                    b.Property<long>("CreateTimeRecord")
                        .HasColumnType("bigint");

                    b.Property<bool>("DsblRecord")
                        .HasColumnType("bit");

                    b.Property<Guid>("GuidRecord")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("LastUpdatedRecord")
                        .HasColumnType("bigint");

                    b.HasKey("IdRecord");

                    b.HasIndex("APV_idRequestInformation");

                    b.HasIndex("APV_idUserAction");

                    b.HasIndex("APV_idUserInCharge");

                    b.ToTable("M_Approve");
                });

            modelBuilder.Entity("Cheetah_DataAccess.Masters.M_CallWebService", b =>
                {
                    b.Property<long>("IdRecord")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdRecord"));

                    b.Property<string>("CWS_JsonInputBody")
                        .HasColumnType("ntext");

                    b.Property<long?>("CWS_RequestInformationIdRecord")
                        .HasColumnType("bigint");

                    b.Property<string>("CWS_URL")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool?>("CWS_WSResult")
                        .HasColumnType("bit");

                    b.Property<int?>("CWS_WSResult_Code")
                        .HasColumnType("int");

                    b.Property<string>("CWS_WSResult_Desc")
                        .HasMaxLength(2500)
                        .HasColumnType("nvarchar(2500)");

                    b.Property<long>("CWS_idParameterList")
                        .HasColumnType("bigint");

                    b.Property<long>("CreateTimeRecord")
                        .HasColumnType("bigint");

                    b.Property<bool>("DsblRecord")
                        .HasColumnType("bit");

                    b.Property<Guid>("GuidRecord")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("LastUpdatedRecord")
                        .HasColumnType("bigint");

                    b.HasKey("IdRecord");

                    b.HasIndex("CWS_RequestInformationIdRecord");

                    b.HasIndex("CWS_idParameterList");

                    b.ToTable("M_CallWebService");
                });

            modelBuilder.Entity("Cheetah_DataAccess.Masters.M_RequestInformation", b =>
                {
                    b.Property<long>("IdRecord")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdRecord"));

                    b.Property<long>("CreateTimeRecord")
                        .HasColumnType("bigint");

                    b.Property<bool>("DsblRecord")
                        .HasColumnType("bit");

                    b.Property<Guid>("GuidRecord")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IdWorkItem")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsTest")
                        .HasColumnType("bit");

                    b.Property<long?>("LastUpdatedRecord")
                        .HasColumnType("bigint");

                    b.Property<long?>("RI_ActiveidProcessEndorsement")
                        .HasColumnType("bigint");

                    b.Property<string>("RI_Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("RI_AlborzSHare")
                        .HasColumnType("bit");

                    b.Property<byte?>("RI_Attachment")
                        .HasColumnType("tinyint");

                    b.Property<bool?>("RI_ConditionDrug")
                        .HasColumnType("bit");

                    b.Property<bool?>("RI_ConditionFMCG")
                        .HasColumnType("bit");

                    b.Property<bool?>("RI_ConditionOccur1")
                        .HasColumnType("bit");

                    b.Property<bool?>("RI_ConditionOccur2")
                        .HasColumnType("bit");

                    b.Property<bool?>("RI_ConditionOccur3")
                        .HasColumnType("bit");

                    b.Property<bool?>("RI_ConditionOccur4")
                        .HasColumnType("bit");

                    b.Property<bool?>("RI_ConditionOccur5")
                        .HasColumnType("bit");

                    b.Property<string>("RI_CurrentUserNames")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("RI_ERPBranchs")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("RI_ERPID")
                        .HasColumnType("bigint");

                    b.Property<string>("RI_ERPKindID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RI_Inputuser1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("RI_IsCancelled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RI_LastTaskSentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RI_LastTimeModify")
                        .HasColumnType("datetime2");

                    b.Property<string>("RI_LastUserComment")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("RI_NewDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RI_OldDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RI_OutputVar1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RI_OutputVar2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RI_OutputVar3")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RI_OutputVar4")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RI_OutputVar5")
                        .HasMaxLength(2500)
                        .HasColumnType("nvarchar(2500)");

                    b.Property<byte?>("RI_PE_Level")
                        .HasColumnType("tinyint");

                    b.Property<string>("RI_People")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("RI_Person")
                        .HasColumnType("bigint");

                    b.Property<string>("RI_ProcessVar1")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("RI_ProcessVar2")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("RI_ProcessVar3")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("RI_ProcessVar4")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("RI_ProcessVar5")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<long?>("RI_RejectReason")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("RI_RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RI_RequestFinishDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("RI_RequestID")
                        .HasColumnType("bigint");

                    b.Property<string>("RI_RequestNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RI_RequestSubject")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool?>("RI_SupplierSHare")
                        .HasColumnType("bit");

                    b.Property<string>("RI_TaskName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RI_UserComment")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("RI_UserNameCreator")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RI_ValidUserAction")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("RI_WS_CurrentId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("RI_WS_Result")
                        .HasColumnType("bit");

                    b.Property<int?>("RI_WS_Result_Code")
                        .HasColumnType("int");

                    b.Property<string>("RI_WS_Result_Desc")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<int?>("RI_WS_TryNum")
                        .HasColumnType("int");

                    b.Property<long?>("RI_idArea")
                        .HasColumnType("bigint");

                    b.Property<long?>("RI_idCreator")
                        .HasColumnType("bigint");

                    b.Property<long?>("RI_idExpertUser")
                        .HasColumnType("bigint");

                    b.Property<long?>("RI_idLastUserAction")
                        .HasColumnType("bigint");

                    b.Property<long?>("RI_idLastUserInCharge")
                        .HasColumnType("bigint");

                    b.Property<long?>("RI_idLocation")
                        .HasColumnType("bigint");

                    b.Property<long?>("RI_idProcessState")
                        .HasColumnType("bigint");

                    b.Property<long?>("RI_idRequestTitle")
                        .HasColumnType("bigint");

                    b.Property<long?>("RI_idRequestType")
                        .HasColumnType("bigint");

                    b.Property<long?>("RI_idRequestor")
                        .HasColumnType("bigint");

                    b.Property<long?>("RI_idSubRequestTitle")
                        .HasColumnType("bigint");

                    b.Property<long?>("RI_idUnitType")
                        .HasColumnType("bigint");

                    b.Property<long?>("RI_idUserAction")
                        .HasColumnType("bigint");

                    b.HasKey("IdRecord");

                    b.HasIndex("RI_ActiveidProcessEndorsement");

                    b.HasIndex("RI_idArea");

                    b.HasIndex("RI_idCreator");

                    b.HasIndex("RI_idExpertUser");

                    b.HasIndex("RI_idLastUserAction");

                    b.HasIndex("RI_idLastUserInCharge");

                    b.HasIndex("RI_idLocation");

                    b.HasIndex("RI_idProcessState");

                    b.HasIndex("RI_idRequestTitle");

                    b.HasIndex("RI_idRequestType");

                    b.HasIndex("RI_idRequestor");

                    b.HasIndex("RI_idSubRequestTitle");

                    b.HasIndex("RI_idUserAction");

                    b.ToTable("M_RequestInformation");
                });

            modelBuilder.Entity("Cheetah_DataAccess.Masters.M_UserActionsProcess", b =>
                {
                    b.Property<long>("IdRecord")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdRecord"));

                    b.Property<long>("CreateTimeRecord")
                        .HasColumnType("bigint");

                    b.Property<bool>("DsblRecord")
                        .HasColumnType("bit");

                    b.Property<Guid>("GuidRecord")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("LastUpdatedRecord")
                        .HasColumnType("bigint");

                    b.Property<bool?>("UAP_Automation")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UAP_CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UAP_IdentificationCode_input")
                        .HasMaxLength(215)
                        .HasColumnType("nvarchar(215)");

                    b.Property<string>("UAP_Receiver_input")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("UAP_SMS")
                        .HasColumnType("bit");

                    b.Property<bool?>("UAP_SendERP")
                        .HasColumnType("bit");

                    b.Property<bool?>("UAP_SendLetterResponse")
                        .HasColumnType("bit");

                    b.Property<bool?>("UAP_SendNotifyERP")
                        .HasColumnType("bit");

                    b.Property<string>("UAP_Subject_input")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UAP_TextBody_input")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<long?>("UAP_idCurrentPE")
                        .HasColumnType("bigint");

                    b.Property<long?>("UAP_idRequestTitle")
                        .HasColumnType("bigint");

                    b.Property<string>("UAP_sender_input")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("idRequestInformation")
                        .HasColumnType("bigint");

                    b.HasKey("IdRecord");

                    b.HasIndex("UAP_idCurrentPE");

                    b.HasIndex("UAP_idRequestTitle");

                    b.HasIndex("idRequestInformation");

                    b.ToTable("M_UserActionsProcess");
                });

            modelBuilder.Entity("Cheetah_DataAccess.Parameters.P_ParameterList", b =>
                {
                    b.Property<long>("IdRecord")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdRecord"));

                    b.Property<long>("CreateTimeRecord")
                        .HasColumnType("bigint");

                    b.Property<bool>("DsblRecord")
                        .HasColumnType("bit");

                    b.Property<Guid>("GuidRecord")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("LastUpdatedRecord")
                        .HasColumnType("bigint");

                    b.Property<long>("PCode")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("PCost")
                        .HasColumnType("numeric");

                    b.Property<string>("PDescription")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<long?>("PERPCode")
                        .HasColumnType("bigint");

                    b.Property<long>("PIndex")
                        .HasColumnType("bigint");

                    b.Property<string>("PName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdRecord");

                    b.ToTable("P_ParameterList");
                });

            modelBuilder.Entity("Cheetah_DataAccess.Parameters.P_ParameterType", b =>
                {
                    b.Property<long>("IdRecord")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdRecord"));

                    b.Property<long>("CreateTimeRecord")
                        .HasColumnType("bigint");

                    b.Property<bool>("DsblRecord")
                        .HasColumnType("bit");

                    b.Property<Guid>("GuidRecord")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("LastUpdatedRecord")
                        .HasColumnType("bigint");

                    b.Property<long>("PCode")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("PCost")
                        .HasColumnType("numeric");

                    b.Property<string>("PDescription")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<long?>("PERPCode")
                        .HasColumnType("bigint");

                    b.Property<long>("PIndex")
                        .HasColumnType("bigint");

                    b.Property<string>("PName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("P_ParameterListIdRecord")
                        .HasColumnType("bigint");

                    b.HasKey("IdRecord");

                    b.HasIndex("P_ParameterListIdRecord");

                    b.ToTable("P_ParameterType");
                });

            modelBuilder.Entity("Cheetah_DataAccess.Parameters.P_PositionOrganization", b =>
                {
                    b.Property<long>("IdRecord")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdRecord"));

                    b.Property<long>("CreateTimeRecord")
                        .HasColumnType("bigint");

                    b.Property<bool>("DsblRecord")
                        .HasColumnType("bit");

                    b.Property<Guid>("GuidRecord")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("LastUpdatedRecord")
                        .HasColumnType("bigint");

                    b.Property<long>("PCode")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("PCost")
                        .HasColumnType("numeric");

                    b.Property<string>("PDescription")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<long?>("PERPCode")
                        .HasColumnType("bigint");

                    b.Property<long>("PIndex")
                        .HasColumnType("bigint");

                    b.Property<string>("PName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PSO_FMCGRole")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("PSO_Group")
                        .HasColumnType("bit");

                    b.Property<string>("PSO_MedicineRole")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PSO_User")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("PSO_idRole")
                        .HasColumnType("bigint");

                    b.Property<long?>("PSO_idRole2")
                        .HasColumnType("bigint");

                    b.HasKey("IdRecord");

                    b.HasIndex("PSO_idRole");

                    b.HasIndex("PSO_idRole2");

                    b.ToTable("P_PositionOrganization");
                });

            modelBuilder.Entity("Cheetah_DataAccess.Parameters.P_ProcessEndorsement", b =>
                {
                    b.Property<long>("IdRecord")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdRecord"));

                    b.Property<long>("CreateTimeRecord")
                        .HasColumnType("bigint");

                    b.Property<bool>("DsblRecord")
                        .HasColumnType("bit");

                    b.Property<Guid>("GuidRecord")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("LastUpdatedRecord")
                        .HasColumnType("bigint");

                    b.Property<long>("PCode")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("PCost")
                        .HasColumnType("numeric");

                    b.Property<string>("PDescription")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<long?>("PERPCode")
                        .HasColumnType("bigint");

                    b.Property<long>("PIndex")
                        .HasColumnType("bigint");

                    b.Property<string>("PName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("PSE_Active")
                        .HasColumnType("bit");

                    b.Property<bool?>("PSE_Automation")
                        .HasColumnType("bit");

                    b.Property<bool?>("PSE_CompanySHare")
                        .HasColumnType("bit");

                    b.Property<bool?>("PSE_ConditionDrug")
                        .HasColumnType("bit");

                    b.Property<bool?>("PSE_ConditionFMCG")
                        .HasColumnType("bit");

                    b.Property<bool?>("PSE_Conditional")
                        .HasColumnType("bit");

                    b.Property<bool?>("PSE_Conditional2")
                        .HasColumnType("bit");

                    b.Property<bool?>("PSE_Conditional3")
                        .HasColumnType("bit");

                    b.Property<bool?>("PSE_Conditional4")
                        .HasColumnType("bit");

                    b.Property<bool?>("PSE_Conditional5")
                        .HasColumnType("bit");

                    b.Property<bool?>("PSE_Mail")
                        .HasColumnType("bit");

                    b.Property<bool?>("PSE_SMS")
                        .HasColumnType("bit");

                    b.Property<bool?>("PSE_SendAll")
                        .HasColumnType("bit");

                    b.Property<string>("PSE_SubRequestTitles")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("PSE_SupplierSHare")
                        .HasColumnType("bit");

                    b.Property<string>("PSE_TaskName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("PSE_Transcript")
                        .HasColumnType("bit");

                    b.Property<long?>("PSE_UserRelationship")
                        .HasMaxLength(50)
                        .HasColumnType("bigint");

                    b.Property<string>("PSE_ValidOutput")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PSE_ValidUserAction")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("PSE_idExpertUser")
                        .HasColumnType("bigint");

                    b.Property<long?>("PSE_idPON")
                        .HasColumnType("bigint");

                    b.Property<long?>("PSE_idProcessState")
                        .HasColumnType("bigint");

                    b.Property<long?>("PSE_idRequestTitle")
                        .HasColumnType("bigint");

                    b.HasKey("IdRecord");

                    b.HasIndex("PSE_idExpertUser");

                    b.HasIndex("PSE_idPON");

                    b.HasIndex("PSE_idProcessState");

                    b.HasIndex("PSE_idRequestTitle");

                    b.ToTable("P_ProcessEndorsement");
                });

            modelBuilder.Entity("Cheetah_DataAccess.Parameters.P_ProcessState", b =>
                {
                    b.Property<long>("IdRecord")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdRecord"));

                    b.Property<long>("CreateTimeRecord")
                        .HasColumnType("bigint");

                    b.Property<bool>("DsblRecord")
                        .HasColumnType("bit");

                    b.Property<Guid>("GuidRecord")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("LastUpdatedRecord")
                        .HasColumnType("bigint");

                    b.Property<long>("PCode")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("PCost")
                        .HasColumnType("numeric");

                    b.Property<string>("PDescription")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<long?>("PERPCode")
                        .HasColumnType("bigint");

                    b.Property<long>("PIndex")
                        .HasColumnType("bigint");

                    b.Property<string>("PName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdRecord");

                    b.ToTable("P_ProcessState");
                });

            modelBuilder.Entity("Cheetah_DataAccess.Parameters.P_RequestTitle", b =>
                {
                    b.Property<long>("IdRecord")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdRecord"));

                    b.Property<long>("CreateTimeRecord")
                        .HasColumnType("bigint");

                    b.Property<bool>("DsblRecord")
                        .HasColumnType("bit");

                    b.Property<Guid>("GuidRecord")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("LastUpdatedRecord")
                        .HasColumnType("bigint");

                    b.Property<long>("PCode")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("PCost")
                        .HasColumnType("numeric");

                    b.Property<string>("PDescription")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<long?>("PERPCode")
                        .HasColumnType("bigint");

                    b.Property<long>("PIndex")
                        .HasColumnType("bigint");

                    b.Property<string>("PName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("RT_AnotherRequester")
                        .HasColumnType("bit");

                    b.Property<bool?>("RT_CheckList")
                        .HasColumnType("bit");

                    b.Property<string>("RT_ConditionOccur")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RT_ConditionOccur2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RT_ConditionOccur3")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RT_ConditionOccur4")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RT_ConditionOccur5")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("RT_ERP")
                        .HasColumnType("bit");

                    b.Property<string>("RT_OutputVar1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RT_OutputVar2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RT_OutputVar3")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RT_OutputVar4")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RT_OutputVar5")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("RT_RemoveRequestorApproval")
                        .HasColumnType("bit");

                    b.Property<bool?>("RT_ShowSupport")
                        .HasColumnType("bit");

                    b.HasKey("IdRecord");

                    b.ToTable("P_RequestTitle");
                });

            modelBuilder.Entity("Cheetah_DataAccess.Parameters.P_RequestType", b =>
                {
                    b.Property<long>("IdRecord")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdRecord"));

                    b.Property<long>("CreateTimeRecord")
                        .HasColumnType("bigint");

                    b.Property<bool>("DsblRecord")
                        .HasColumnType("bit");

                    b.Property<Guid>("GuidRecord")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("LastUpdatedRecord")
                        .HasColumnType("bigint");

                    b.Property<long>("PCode")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("PCost")
                        .HasColumnType("numeric");

                    b.Property<string>("PDescription")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<long?>("PERPCode")
                        .HasColumnType("bigint");

                    b.Property<long>("PIndex")
                        .HasColumnType("bigint");

                    b.Property<string>("PName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdRecord");

                    b.ToTable("P_RequestType");
                });

            modelBuilder.Entity("Cheetah_DataAccess.Parameters.P_SubRequestTitle", b =>
                {
                    b.Property<long>("IdRecord")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdRecord"));

                    b.Property<long>("CreateTimeRecord")
                        .HasColumnType("bigint");

                    b.Property<bool>("DsblRecord")
                        .HasColumnType("bit");

                    b.Property<Guid>("GuidRecord")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("LastUpdatedRecord")
                        .HasColumnType("bigint");

                    b.Property<long>("PCode")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("PCost")
                        .HasColumnType("numeric");

                    b.Property<string>("PDescription")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<long?>("PERPCode")
                        .HasColumnType("bigint");

                    b.Property<long>("PIndex")
                        .HasColumnType("bigint");

                    b.Property<string>("PName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("SBT_idRequestTitles")
                        .HasColumnType("bigint");

                    b.HasKey("IdRecord");

                    b.HasIndex("SBT_idRequestTitles");

                    b.ToTable("P_SubRequestTitle");
                });

            modelBuilder.Entity("Cheetah_DataAccess.Parameters.P_UserAction", b =>
                {
                    b.Property<long>("IdRecord")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdRecord"));

                    b.Property<long>("CreateTimeRecord")
                        .HasColumnType("bigint");

                    b.Property<bool>("DsblRecord")
                        .HasColumnType("bit");

                    b.Property<Guid>("GuidRecord")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("LastUpdatedRecord")
                        .HasColumnType("bigint");

                    b.Property<long>("PCode")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("PCost")
                        .HasColumnType("numeric");

                    b.Property<string>("PDescription")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<long?>("PERPCode")
                        .HasColumnType("bigint");

                    b.Property<long>("PIndex")
                        .HasColumnType("bigint");

                    b.Property<string>("PName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UA_Abbreviation")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UA_ValidActions")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("UA_idUserActionGroup")
                        .HasColumnType("bigint");

                    b.HasKey("IdRecord");

                    b.HasIndex("UA_idUserActionGroup");

                    b.ToTable("P_UserAction");
                });

            modelBuilder.Entity("Cheetah_DataAccess.Parameters.P_UserActionGroup", b =>
                {
                    b.Property<long>("IdRecord")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdRecord"));

                    b.Property<long>("CreateTimeRecord")
                        .HasColumnType("bigint");

                    b.Property<bool>("DsblRecord")
                        .HasColumnType("bit");

                    b.Property<Guid>("GuidRecord")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("LastUpdatedRecord")
                        .HasColumnType("bigint");

                    b.Property<long>("PCode")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("PCost")
                        .HasColumnType("numeric");

                    b.Property<string>("PDescription")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<long?>("PERPCode")
                        .HasColumnType("bigint");

                    b.Property<long>("PIndex")
                        .HasColumnType("bigint");

                    b.Property<string>("PName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdRecord");

                    b.ToTable("P_UserActionGroup");
                });

            modelBuilder.Entity("Cheetah_DataAccess.Systems.S_Area", b =>
                {
                    b.Property<long>("IdRecord")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdRecord"));

                    b.Property<long>("CreateTimeRecord")
                        .HasColumnType("bigint");

                    b.Property<bool>("DsblRecord")
                        .HasColumnType("bit");

                    b.Property<Guid>("GuidRecord")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("LastUpdatedRecord")
                        .HasColumnType("bigint");

                    b.Property<long>("PCode")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("PCost")
                        .HasColumnType("numeric");

                    b.Property<string>("PDescription")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<long?>("PERPCode")
                        .HasColumnType("bigint");

                    b.Property<long>("PIndex")
                        .HasColumnType("bigint");

                    b.Property<string>("PName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdRecord");

                    b.ToTable("S_Area");
                });

            modelBuilder.Entity("Cheetah_DataAccess.Systems.S_Location", b =>
                {
                    b.Property<long>("IdRecord")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdRecord"));

                    b.Property<long>("CreateTimeRecord")
                        .HasColumnType("bigint");

                    b.Property<bool>("DsblRecord")
                        .HasColumnType("bit");

                    b.Property<Guid>("GuidRecord")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("LastUpdatedRecord")
                        .HasColumnType("bigint");

                    b.Property<long>("PCode")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("PCost")
                        .HasColumnType("numeric");

                    b.Property<string>("PDescription")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<long?>("PERPCode")
                        .HasColumnType("bigint");

                    b.Property<long>("PIndex")
                        .HasColumnType("bigint");

                    b.Property<string>("PName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdRecord");

                    b.ToTable("S_Location");
                });

            modelBuilder.Entity("Cheetah_DataAccess.Systems.S_OrgPosition", b =>
                {
                    b.Property<long>("IdRecord")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdRecord"));

                    b.Property<long>("CreateTimeRecord")
                        .HasColumnType("bigint");

                    b.Property<bool>("DsblRecord")
                        .HasColumnType("bit");

                    b.Property<Guid>("GuidRecord")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("LastUpdatedRecord")
                        .HasColumnType("bigint");

                    b.Property<long>("PCode")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("PCost")
                        .HasColumnType("numeric");

                    b.Property<string>("PDescription")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<long?>("PERPCode")
                        .HasColumnType("bigint");

                    b.Property<long>("PIndex")
                        .HasColumnType("bigint");

                    b.Property<string>("PName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("POS_idOrg")
                        .HasColumnType("bigint");

                    b.HasKey("IdRecord");

                    b.ToTable("OrgPosition");
                });

            modelBuilder.Entity("Cheetah_DataAccess.Systems.S_Role", b =>
                {
                    b.Property<long>("IdRecord")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdRecord"));

                    b.Property<long>("CreateTimeRecord")
                        .HasColumnType("bigint");

                    b.Property<bool>("DsblRecord")
                        .HasColumnType("bit");

                    b.Property<Guid>("GuidRecord")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("LastUpdatedRecord")
                        .HasColumnType("bigint");

                    b.Property<long>("PCode")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("PCost")
                        .HasColumnType("numeric");

                    b.Property<string>("PDescription")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<long?>("PERPCode")
                        .HasColumnType("bigint");

                    b.Property<long>("PIndex")
                        .HasColumnType("bigint");

                    b.Property<string>("PName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdRecord");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("Cheetah_DataAccess.Systems.S_User", b =>
                {
                    b.Property<long>("IdRecord")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdRecord"));

                    b.Property<long>("CreateTimeRecord")
                        .HasColumnType("bigint");

                    b.Property<bool>("DsblRecord")
                        .HasColumnType("bit");

                    b.Property<Guid>("GuidRecord")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("LastUpdatedRecord")
                        .HasColumnType("bigint");

                    b.Property<long>("PCode")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("PCost")
                        .HasColumnType("numeric");

                    b.Property<string>("PDescription")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<long?>("PERPCode")
                        .HasColumnType("bigint");

                    b.Property<long>("PIndex")
                        .HasColumnType("bigint");

                    b.Property<string>("PName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("User_Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("User_ContactCell")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("User_ContactEmail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("User_ContactMessenger")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("User_CreatedCasesSkipAssigRules")
                        .HasColumnType("bit");

                    b.Property<byte?>("User_DelegateEnabled")
                        .HasColumnType("tinyint");

                    b.Property<string>("User_DistrictManager_RelatedL")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("User_Domain")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<bool?>("User_Enabled")
                        .HasColumnType("bit");

                    b.Property<byte?>("User_EnabledForAssignation")
                        .HasColumnType("tinyint");

                    b.Property<string>("User_FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("User_FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("User_IDPersonel")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("User_InternalPhone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("User_IsNeedUpperApprove")
                        .HasColumnType("bit");

                    b.Property<string>("User_LDAPDescription")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("User_LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("User_NationalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool?>("User_NotifByCell")
                        .HasColumnType("bit");

                    b.Property<bool?>("User_NotifByEmail")
                        .HasColumnType("bit");

                    b.Property<bool?>("User_NotifByMessenger")
                        .HasColumnType("bit");

                    b.Property<bool?>("User_OfflineForms")
                        .HasColumnType("bit");

                    b.Property<decimal?>("User_OvertimeCost")
                        .HasColumnType("money");

                    b.Property<string>("User_RelatedLocation")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("User_SubUsers")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("User_Temp_IDPersonel")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("User_UserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte?>("User_UserPicture")
                        .HasColumnType("tinyint");

                    b.Property<int?>("User_UserStartPage")
                        .HasColumnType("int");

                    b.Property<long?>("User_idArea")
                        .HasColumnType("bigint");

                    b.Property<long?>("User_idBossUser")
                        .HasColumnType("bigint");

                    b.Property<long?>("User_idDefaultPosition")
                        .HasColumnType("bigint");

                    b.Property<long?>("User_idDelegate")
                        .HasColumnType("bigint");

                    b.Property<long?>("User_idFirstApprover")
                        .HasColumnType("bigint");

                    b.Property<long?>("User_idFirstRoleUser")
                        .HasColumnType("bigint");

                    b.Property<long?>("User_idLocation")
                        .HasColumnType("bigint");

                    b.Property<long?>("User_idSecondApprover")
                        .HasColumnType("bigint");

                    b.Property<long?>("User_idTimeZone")
                        .HasColumnType("bigint");

                    b.Property<long?>("User_idUnitType")
                        .HasColumnType("bigint");

                    b.Property<long?>("User_idWorkingTimeSchema")
                        .HasColumnType("bigint");

                    b.Property<int?>("User_language")
                        .HasColumnType("int");

                    b.HasKey("IdRecord");

                    b.HasIndex("User_idArea");

                    b.HasIndex("User_idBossUser");

                    b.HasIndex("User_idDefaultPosition");

                    b.HasIndex("User_idDelegate");

                    b.HasIndex("User_idFirstApprover");

                    b.HasIndex("User_idFirstRoleUser");

                    b.HasIndex("User_idLocation");

                    b.HasIndex("User_idSecondApprover");

                    b.ToTable("S_User");
                });

            modelBuilder.Entity("Cheetah_DataAccess.CopyProduct", b =>
                {
                    b.HasOne("Cheetah_DataAccess.CopyROLE", "copyROLE")
                        .WithMany()
                        .HasForeignKey("idRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("copyROLE");
                });

            modelBuilder.Entity("Cheetah_DataAccess.Masters.M_Approve", b =>
                {
                    b.HasOne("Cheetah_DataAccess.Masters.M_RequestInformation", "APV_RequestInformation")
                        .WithMany("RI_Approves")
                        .HasForeignKey("APV_idRequestInformation");

                    b.HasOne("Cheetah_DataAccess.Parameters.P_UserAction", "APV_UserAction")
                        .WithMany()
                        .HasForeignKey("APV_idUserAction");

                    b.HasOne("Cheetah_DataAccess.Systems.S_User", "APV_UserInCharge")
                        .WithMany()
                        .HasForeignKey("APV_idUserInCharge");

                    b.Navigation("APV_RequestInformation");

                    b.Navigation("APV_UserAction");

                    b.Navigation("APV_UserInCharge");
                });

            modelBuilder.Entity("Cheetah_DataAccess.Masters.M_CallWebService", b =>
                {
                    b.HasOne("Cheetah_DataAccess.Masters.M_RequestInformation", "CWS_RequestInformation")
                        .WithMany("RI_CallWebServices")
                        .HasForeignKey("CWS_RequestInformationIdRecord");

                    b.HasOne("Cheetah_DataAccess.Parameters.P_ParameterList", "CWS_ParameterList")
                        .WithMany()
                        .HasForeignKey("CWS_idParameterList")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CWS_ParameterList");

                    b.Navigation("CWS_RequestInformation");
                });

            modelBuilder.Entity("Cheetah_DataAccess.Masters.M_RequestInformation", b =>
                {
                    b.HasOne("Cheetah_DataAccess.Parameters.P_ProcessEndorsement", "RI_ActiveProcessEndorsement")
                        .WithMany()
                        .HasForeignKey("RI_ActiveidProcessEndorsement");

                    b.HasOne("Cheetah_DataAccess.Systems.S_Area", "RI_Area")
                        .WithMany()
                        .HasForeignKey("RI_idArea");

                    b.HasOne("Cheetah_DataAccess.Systems.S_User", "RI_Creator")
                        .WithMany()
                        .HasForeignKey("RI_idCreator");

                    b.HasOne("Cheetah_DataAccess.Systems.S_User", "RI_ExpertUser")
                        .WithMany()
                        .HasForeignKey("RI_idExpertUser");

                    b.HasOne("Cheetah_DataAccess.Parameters.P_UserAction", "RI_LastUserAction")
                        .WithMany()
                        .HasForeignKey("RI_idLastUserAction");

                    b.HasOne("Cheetah_DataAccess.Systems.S_User", "RI_LastUserInCharge")
                        .WithMany()
                        .HasForeignKey("RI_idLastUserInCharge");

                    b.HasOne("Cheetah_DataAccess.Systems.S_Location", "RI_Location")
                        .WithMany()
                        .HasForeignKey("RI_idLocation");

                    b.HasOne("Cheetah_DataAccess.Parameters.P_ProcessState", "RI_ProcessState")
                        .WithMany()
                        .HasForeignKey("RI_idProcessState");

                    b.HasOne("Cheetah_DataAccess.Parameters.P_RequestTitle", "RI_RequestTitle")
                        .WithMany()
                        .HasForeignKey("RI_idRequestTitle");

                    b.HasOne("Cheetah_DataAccess.Parameters.P_RequestType", "RI_RequestType")
                        .WithMany()
                        .HasForeignKey("RI_idRequestType");

                    b.HasOne("Cheetah_DataAccess.Systems.S_User", "RI_Requestor")
                        .WithMany()
                        .HasForeignKey("RI_idRequestor");

                    b.HasOne("Cheetah_DataAccess.Parameters.P_SubRequestTitle", "RI_SubRequestTitle")
                        .WithMany()
                        .HasForeignKey("RI_idSubRequestTitle");

                    b.HasOne("Cheetah_DataAccess.Parameters.P_UserAction", "RI_UserAction")
                        .WithMany()
                        .HasForeignKey("RI_idUserAction");

                    b.Navigation("RI_ActiveProcessEndorsement");

                    b.Navigation("RI_Area");

                    b.Navigation("RI_Creator");

                    b.Navigation("RI_ExpertUser");

                    b.Navigation("RI_LastUserAction");

                    b.Navigation("RI_LastUserInCharge");

                    b.Navigation("RI_Location");

                    b.Navigation("RI_ProcessState");

                    b.Navigation("RI_RequestTitle");

                    b.Navigation("RI_RequestType");

                    b.Navigation("RI_Requestor");

                    b.Navigation("RI_SubRequestTitle");

                    b.Navigation("RI_UserAction");
                });

            modelBuilder.Entity("Cheetah_DataAccess.Masters.M_UserActionsProcess", b =>
                {
                    b.HasOne("Cheetah_DataAccess.Parameters.P_ProcessEndorsement", "UAP_CurrentPE")
                        .WithMany()
                        .HasForeignKey("UAP_idCurrentPE");

                    b.HasOne("Cheetah_DataAccess.Parameters.P_RequestTitle", "UAP_RequestTitle")
                        .WithMany()
                        .HasForeignKey("UAP_idRequestTitle");

                    b.HasOne("Cheetah_DataAccess.Masters.M_RequestInformation", "UAP_RequestInformation")
                        .WithMany("RI_UserActionsProcesses")
                        .HasForeignKey("idRequestInformation");

                    b.Navigation("UAP_CurrentPE");

                    b.Navigation("UAP_RequestInformation");

                    b.Navigation("UAP_RequestTitle");
                });

            modelBuilder.Entity("Cheetah_DataAccess.Parameters.P_ParameterType", b =>
                {
                    b.HasOne("Cheetah_DataAccess.Parameters.P_ParameterList", null)
                        .WithMany("PL_ParameterType")
                        .HasForeignKey("P_ParameterListIdRecord");
                });

            modelBuilder.Entity("Cheetah_DataAccess.Parameters.P_PositionOrganization", b =>
                {
                    b.HasOne("Cheetah_DataAccess.Systems.S_Role", "PSO_Role")
                        .WithMany()
                        .HasForeignKey("PSO_idRole");

                    b.HasOne("Cheetah_DataAccess.Systems.S_Role", "PSO_Role2")
                        .WithMany()
                        .HasForeignKey("PSO_idRole2");

                    b.Navigation("PSO_Role");

                    b.Navigation("PSO_Role2");
                });

            modelBuilder.Entity("Cheetah_DataAccess.Parameters.P_ProcessEndorsement", b =>
                {
                    b.HasOne("Cheetah_DataAccess.Systems.S_User", "PSE_ExpertUser")
                        .WithMany()
                        .HasForeignKey("PSE_idExpertUser");

                    b.HasOne("Cheetah_DataAccess.Parameters.P_PositionOrganization", "PSE_PON")
                        .WithMany()
                        .HasForeignKey("PSE_idPON");

                    b.HasOne("Cheetah_DataAccess.Parameters.P_ProcessState", "PSE_ProcessState")
                        .WithMany()
                        .HasForeignKey("PSE_idProcessState");

                    b.HasOne("Cheetah_DataAccess.Parameters.P_RequestTitle", "PSE_RequestTitle")
                        .WithMany()
                        .HasForeignKey("PSE_idRequestTitle");

                    b.Navigation("PSE_ExpertUser");

                    b.Navigation("PSE_PON");

                    b.Navigation("PSE_ProcessState");

                    b.Navigation("PSE_RequestTitle");
                });

            modelBuilder.Entity("Cheetah_DataAccess.Parameters.P_SubRequestTitle", b =>
                {
                    b.HasOne("Cheetah_DataAccess.Parameters.P_RequestTitle", "SBT_RequestTitles")
                        .WithMany()
                        .HasForeignKey("SBT_idRequestTitles");

                    b.Navigation("SBT_RequestTitles");
                });

            modelBuilder.Entity("Cheetah_DataAccess.Parameters.P_UserAction", b =>
                {
                    b.HasOne("Cheetah_DataAccess.Parameters.P_UserActionGroup", "UA_UserActionGroup")
                        .WithMany()
                        .HasForeignKey("UA_idUserActionGroup");

                    b.Navigation("UA_UserActionGroup");
                });

            modelBuilder.Entity("Cheetah_DataAccess.Systems.S_User", b =>
                {
                    b.HasOne("Cheetah_DataAccess.Systems.S_Area", "User_Area")
                        .WithMany()
                        .HasForeignKey("User_idArea");

                    b.HasOne("Cheetah_DataAccess.Systems.S_User", "User_BossUser")
                        .WithMany()
                        .HasForeignKey("User_idBossUser");

                    b.HasOne("Cheetah_DataAccess.Systems.S_OrgPosition", "User_DefaultPosition")
                        .WithMany()
                        .HasForeignKey("User_idDefaultPosition");

                    b.HasOne("Cheetah_DataAccess.Systems.S_User", "User_Delegate")
                        .WithMany()
                        .HasForeignKey("User_idDelegate");

                    b.HasOne("Cheetah_DataAccess.Systems.S_User", "User_FirstApprover")
                        .WithMany()
                        .HasForeignKey("User_idFirstApprover");

                    b.HasOne("Cheetah_DataAccess.Systems.S_User", "User_FirstRoleUser")
                        .WithMany()
                        .HasForeignKey("User_idFirstRoleUser");

                    b.HasOne("Cheetah_DataAccess.Systems.S_Location", "User_Location")
                        .WithMany()
                        .HasForeignKey("User_idLocation");

                    b.HasOne("Cheetah_DataAccess.Systems.S_User", "User_SecondApprover")
                        .WithMany()
                        .HasForeignKey("User_idSecondApprover");

                    b.Navigation("User_Area");

                    b.Navigation("User_BossUser");

                    b.Navigation("User_DefaultPosition");

                    b.Navigation("User_Delegate");

                    b.Navigation("User_FirstApprover");

                    b.Navigation("User_FirstRoleUser");

                    b.Navigation("User_Location");

                    b.Navigation("User_SecondApprover");
                });

            modelBuilder.Entity("Cheetah_DataAccess.Masters.M_RequestInformation", b =>
                {
                    b.Navigation("RI_Approves");

                    b.Navigation("RI_CallWebServices");

                    b.Navigation("RI_UserActionsProcesses");
                });

            modelBuilder.Entity("Cheetah_DataAccess.Parameters.P_ParameterList", b =>
                {
                    b.Navigation("PL_ParameterType");
                });
#pragma warning restore 612, 618
        }
    }
}
