global using Cheetah.Application.Business.Interfaces;
global using Cheetah.Domain.Common;
global using Cheetah.Domain.Entities.Dimentions;
global using Cheetah.Domain.Entities.Facts;
global using Cheetah.Infrastructure.Persistence;
global using Cheetah.Infrastructure.Persistence.Data;
global using Cheetah_GrpcService;
global using MediatR;
global using Microsoft.AspNetCore.Mvc;
