global using Ardalis.GuardClauses;
global using Ardalis.Result;
global using Ardalis.SharedKernel;
global using Ardalis.Specification;
global using FluentValidation;
global using Mapster;
global using MapsterMapper;
global using MediatR;
global using Microsoft.Extensions.Caching.Memory;
