//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cheetah.Domain.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cheetah.Domain.Resx.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات.
        /// </summary>
        public static string Domain_Description {
            get {
                return ResourceManager.GetString("Domain_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام نمایشی.
        /// </summary>
        public static string Domain_DisplayName {
            get {
                return ResourceManager.GetString("Domain_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعال.
        /// </summary>
        public static string Domain_EnableRecord {
            get {
                return ResourceManager.GetString("Domain_EnableRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد در ERP.
        /// </summary>
        public static string Domain_ERPCode {
            get {
                return ResourceManager.GetString("Domain_ERPCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه.
        /// </summary>
        public static string Domain_Id {
            get {
                return ResourceManager.GetString("Domain_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد ردیف.
        /// </summary>
        public static string Domain_InsertRow {
            get {
                return ResourceManager.GetString("Domain_InsertRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string Domain_Name {
            get {
                return ResourceManager.GetString("Domain_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ردیف &apos;{0}&apos;.
        /// </summary>
        public static string Domain_RowDescription {
            get {
                return ResourceManager.GetString("Domain_RowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اندیس مرتب‌سازی.
        /// </summary>
        public static string Domain_SortIndex {
            get {
                return ResourceManager.GetString("Domain_SortIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جدول {0}.
        /// </summary>
        public static string Domain_TableDescription {
            get {
                return ResourceManager.GetString("Domain_TableDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست جدول‌ها.
        /// </summary>
        public static string Domain_Tablelist {
            get {
                return ResourceManager.GetString("Domain_Tablelist", resourceCulture);
            }
        }
    }
}
