//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cheetah.Core.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cheetah.Core.Resx.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد.
        /// </summary>
        public static string Core_Create {
            get {
                return ResourceManager.GetString("Core_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate.
        /// </summary>
        public static string Core_Duplicate {
            get {
                return ResourceManager.GetString("Core_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست پیشین با شماره رهیگری {0} در چیتا ثبت شده است.
        /// </summary>
        public static string Core_DuplicateErrorCreateRequest {
            get {
                return ResourceManager.GetString("Core_DuplicateErrorCreateRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رکوردی یافت نشد.
        /// </summary>
        public static string Core_NotFound {
            get {
                return ResourceManager.GetString("Core_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Core_Success {
            get {
                return ResourceManager.GetString("Core_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست با شماره رهیگری {0} با موفقیت در چیتا ثبت شد.
        /// </summary>
        public static string Core_SuccessCreateRequest {
            get {
                return ResourceManager.GetString("Core_SuccessCreateRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست با شماره کار {0} با موفقیت در چیتا ارسال شد.
        /// </summary>
        public static string Core_SuccessPerformWorkItem {
            get {
                return ResourceManager.GetString("Core_SuccessPerformWorkItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش.
        /// </summary>
        public static string Core_Update {
            get {
                return ResourceManager.GetString("Core_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیشین فرم با شماره کار {0} در چیتا ارسال شده است.
        /// </summary>
        public static string PreviouslySentError {
            get {
                return ResourceManager.GetString("PreviouslySentError", resourceCulture);
            }
        }
    }
}
