//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cheetah.Presentation.Web.Blazor.Server.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cheetah.Presentation.Web.Blazor.Server.Resx.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اقدام.
        /// </summary>
        public static string BlazorServer_Action {
            get {
                return ResourceManager.GetString("BlazorServer_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اقدامات.
        /// </summary>
        public static string BlazorServer_Actions {
            get {
                return ResourceManager.GetString("BlazorServer_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد.
        /// </summary>
        public static string BlazorServer_Add {
            get {
                return ResourceManager.GetString("BlazorServer_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافه کردن اقدامات.
        /// </summary>
        public static string BlazorServer_AddActions {
            get {
                return ResourceManager.GetString("BlazorServer_AddActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن به لیست شرط‌ها/متغیرها.
        /// </summary>
        public static string BlazorServer_AddConditionAndVariable {
            get {
                return ResourceManager.GetString("BlazorServer_AddConditionAndVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافه کردن اقدام بعدی.
        /// </summary>
        public static string BlazorServer_AddNextAction {
            get {
                return ResourceManager.GetString("BlazorServer_AddNextAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافه کردن شرط‌ها.
        /// </summary>
        public static string BlazorServer_AddToConditions {
            get {
                return ResourceManager.GetString("BlazorServer_AddToConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن فرم.
        /// </summary>
        public static string BlazorServer_AddToTasks {
            get {
                return ResourceManager.GetString("BlazorServer_AddToTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بصورت خودکار ساخته می‌شود.
        /// </summary>
        public static string BlazorServer_AutomaticGenerated {
            get {
                return ResourceManager.GetString("BlazorServer_AutomaticGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انصراف.
        /// </summary>
        public static string BlazorServer_Cancel {
            get {
                return ResourceManager.GetString("BlazorServer_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت درخواست.
        /// </summary>
        public static string BlazorServer_CaseState {
            get {
                return ResourceManager.GetString("BlazorServer_CaseState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار.
        /// </summary>
        public static string BlazorServer_CellValue {
            get {
                return ResourceManager.GetString("BlazorServer_CellValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چیتا.
        /// </summary>
        public static string BlazorServer_Cheetah {
            get {
                return ResourceManager.GetString("BlazorServer_Cheetah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بستن.
        /// </summary>
        public static string BlazorServer_Close {
            get {
                return ResourceManager.GetString("BlazorServer_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شرط.
        /// </summary>
        public static string BlazorServer_Condition {
            get {
                return ResourceManager.GetString("BlazorServer_Condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست شرط‌ها/متغیرها.
        /// </summary>
        public static string BlazorServer_ConditionAndVariableList {
            get {
                return ResourceManager.GetString("BlazorServer_ConditionAndVariableList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شرط‌ها.
        /// </summary>
        public static string BlazorServer_Conditions {
            get {
                return ResourceManager.GetString("BlazorServer_Conditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارتباط با ما.
        /// </summary>
        public static string BlazorServer_ContactUs {
            get {
                return ResourceManager.GetString("BlazorServer_ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد.
        /// </summary>
        public static string BlazorServer_Create {
            get {
                return ResourceManager.GetString("BlazorServer_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا از حذف ردیف اطمینان دارید؟.
        /// </summary>
        public static string BlazorServer_DeleteConformation {
            get {
                return ResourceManager.GetString("BlazorServer_DeleteConformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات.
        /// </summary>
        public static string BlazorServer_Description {
            get {
                return ResourceManager.GetString("BlazorServer_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام نمایشی.
        /// </summary>
        public static string BlazorServer_DisplayName {
            get {
                return ResourceManager.GetString("BlazorServer_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش پارامتر.
        /// </summary>
        public static string BlazorServer_EditParameter {
            get {
                return ResourceManager.GetString("BlazorServer_EditParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رایانامه.
        /// </summary>
        public static string BlazorServer_Email {
            get {
                return ResourceManager.GetString("BlazorServer_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعال.
        /// </summary>
        public static string BlazorServer_Enable {
            get {
                return ResourceManager.GetString("BlazorServer_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعال.
        /// </summary>
        public static string BlazorServer_EnableRecord {
            get {
                return ResourceManager.GetString("BlazorServer_EnableRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد در ERP.
        /// </summary>
        public static string BlazorServer_ERPCode {
            get {
                return ResourceManager.GetString("BlazorServer_ERPCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خروج.
        /// </summary>
        public static string BlazorServer_Exit {
            get {
                return ResourceManager.GetString("BlazorServer_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات تکمیلی.
        /// </summary>
        public static string BlazorServer_ExtraInformation {
            get {
                return ResourceManager.GetString("BlazorServer_ExtraInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلتر.
        /// </summary>
        public static string BlazorServer_Filter {
            get {
                return ResourceManager.GetString("BlazorServer_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نامی که کاربر مشاهده می‌کند.
        /// </summary>
        public static string BlazorServer_ForDisplayName {
            get {
                return ResourceManager.GetString("BlazorServer_ForDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام فرم.
        /// </summary>
        public static string BlazorServer_FormName {
            get {
                return ResourceManager.GetString("BlazorServer_FormName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام سیستمی.
        /// </summary>
        public static string BlazorServer_ForName {
            get {
                return ResourceManager.GetString("BlazorServer_ForName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جهت مرتب‌سازی.
        /// </summary>
        public static string BlazorServer_ForSorting {
            get {
                return ResourceManager.GetString("BlazorServer_ForSorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات عمومی.
        /// </summary>
        public static string BlazorServer_GeneralInformation {
            get {
                return ResourceManager.GetString("BlazorServer_GeneralInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه.
        /// </summary>
        public static string BlazorServer_Id {
            get {
                return ResourceManager.GetString("BlazorServer_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صندوق ورودی.
        /// </summary>
        public static string BlazorServer_Inbox {
            get {
                return ResourceManager.GetString("BlazorServer_Inbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مستقل.
        /// </summary>
        public static string BlazorServer_Independ {
            get {
                return ResourceManager.GetString("BlazorServer_Independ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد ردیف.
        /// </summary>
        public static string BlazorServer_InsertRow {
            get {
                return ResourceManager.GetString("BlazorServer_InsertRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موقعیت.
        /// </summary>
        public static string BlazorServer_Location {
            get {
                return ResourceManager.GetString("BlazorServer_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود.
        /// </summary>
        public static string BlazorServer_Login {
            get {
                return ResourceManager.GetString("BlazorServer_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متن پیام.
        /// </summary>
        public static string BlazorServer_Message {
            get {
                return ResourceManager.GetString("BlazorServer_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طراحی فرآیند.
        /// </summary>
        public static string BlazorServer_ModelDiagram {
            get {
                return ResourceManager.GetString("BlazorServer_ModelDiagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string BlazorServer_Name {
            get {
                return ResourceManager.GetString("BlazorServer_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام و نام خانوادگی.
        /// </summary>
        public static string BlazorServer_NameAndFamily {
            get {
                return ResourceManager.GetString("BlazorServer_NameAndFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست جدید.
        /// </summary>
        public static string BlazorServer_NewMessage {
            get {
                return ResourceManager.GetString("BlazorServer_NewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اقدام های بعدی.
        /// </summary>
        public static string BlazorServer_NextActions {
            get {
                return ResourceManager.GetString("BlazorServer_NextActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما دسترسی ندارید.
        /// </summary>
        public static string BlazorServer_NotAuthorize {
            get {
                return ResourceManager.GetString("BlazorServer_NotAuthorize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چنین صفحه ای پیدا نشد.
        /// </summary>
        public static string BlazorServer_NotFound {
            get {
                return ResourceManager.GetString("BlazorServer_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملگر.
        /// </summary>
        public static string BlazorServer_Operand {
            get {
                return ResourceManager.GetString("BlazorServer_Operand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کارهای انجام شده.
        /// </summary>
        public static string BlazorServer_Outbox {
            get {
                return ResourceManager.GetString("BlazorServer_Outbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پارامتر.
        /// </summary>
        public static string BlazorServer_Parameter {
            get {
                return ResourceManager.GetString("BlazorServer_Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع پارامتر.
        /// </summary>
        public static string BlazorServer_ParameterType {
            get {
                return ResourceManager.GetString("BlazorServer_ParameterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ ایجاد.
        /// </summary>
        public static string BlazorServer_PCreateDate {
            get {
                return ResourceManager.GetString("BlazorServer_PCreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست سمت هایی که در نقش {0} هستند.
        /// </summary>
        public static string BlazorServer_PositionsInRole {
            get {
                return ResourceManager.GetString("BlazorServer_PositionsInRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ دریافت.
        /// </summary>
        public static string BlazorServer_PRecieveDate {
            get {
                return ResourceManager.GetString("BlazorServer_PRecieveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام فرآیند.
        /// </summary>
        public static string BlazorServer_Process {
            get {
                return ResourceManager.GetString("BlazorServer_Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رهگیری.
        /// </summary>
        public static string BlazorServer_RadNumber {
            get {
                return ResourceManager.GetString("BlazorServer_RadNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت‌نام.
        /// </summary>
        public static string BlazorServer_Register {
            get {
                return ResourceManager.GetString("BlazorServer_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست کننده.
        /// </summary>
        public static string BlazorServer_Requestor {
            get {
                return ResourceManager.GetString("BlazorServer_Requestor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازنشانی.
        /// </summary>
        public static string BlazorServer_Reset {
            get {
                return ResourceManager.GetString("BlazorServer_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برگشت.
        /// </summary>
        public static string BlazorServer_Return {
            get {
                return ResourceManager.GetString("BlazorServer_Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام نقش.
        /// </summary>
        public static string BlazorServer_RoleName {
            get {
                return ResourceManager.GetString("BlazorServer_RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ردیف با موفقیت ایجاد شد.
        /// </summary>
        public static string BlazorServer_RowAdded {
            get {
                return ResourceManager.GetString("BlazorServer_RowAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        public static string BlazorServer_RowDelete {
            get {
                return ResourceManager.GetString("BlazorServer_RowDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ردیف &apos;{0}&apos;.
        /// </summary>
        public static string BlazorServer_RowDescId {
            get {
                return ResourceManager.GetString("BlazorServer_RowDescId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات.
        /// </summary>
        public static string BlazorServer_RowDescription {
            get {
                return ResourceManager.GetString("BlazorServer_RowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام نمایشی.
        /// </summary>
        public static string BlazorServer_RowDisplayName {
            get {
                return ResourceManager.GetString("BlazorServer_RowDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش.
        /// </summary>
        public static string BlazorServer_RowEdit {
            get {
                return ResourceManager.GetString("BlazorServer_RowEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه.
        /// </summary>
        public static string BlazorServer_RowId {
            get {
                return ResourceManager.GetString("BlazorServer_RowId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string BlazorServer_RowName {
            get {
                return ResourceManager.GetString("BlazorServer_RowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ردیف {0} با موفقیت ذخیره شد.
        /// </summary>
        public static string BlazorServer_RowSaved {
            get {
                return ResourceManager.GetString("BlazorServer_RowSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ذخیره.
        /// </summary>
        public static string BlazorServer_Save {
            get {
                return ResourceManager.GetString("BlazorServer_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست راهبردهایی که مرتبط با فرآیند {0} هستند.
        /// </summary>
        public static string BlazorServer_ScenariosInProcess {
            get {
                return ResourceManager.GetString("BlazorServer_ScenariosInProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب.
        /// </summary>
        public static string BlazorServer_Select {
            get {
                return ResourceManager.GetString("BlazorServer_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا یک مورد را انتخاب نمایید.
        /// </summary>
        public static string BlazorServer_SelectOneItem {
            get {
                return ResourceManager.GetString("BlazorServer_SelectOneItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب پارامتر.
        /// </summary>
        public static string BlazorServer_SelectParameter {
            get {
                return ResourceManager.GetString("BlazorServer_SelectParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال.
        /// </summary>
        public static string BlazorServer_Send {
            get {
                return ResourceManager.GetString("BlazorServer_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ترتیب.
        /// </summary>
        public static string BlazorServer_SortIndex {
            get {
                return ResourceManager.GetString("BlazorServer_SortIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نظرات و پیشنهادات.
        /// </summary>
        public static string BlazorServer_Suggestion {
            get {
                return ResourceManager.GetString("BlazorServer_Suggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خلاصه درخواست.
        /// </summary>
        public static string BlazorServer_Summary {
            get {
                return ResourceManager.GetString("BlazorServer_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جدول {0}.
        /// </summary>
        public static string BlazorServer_TableDescription {
            get {
                return ResourceManager.GetString("BlazorServer_TableDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست جدول‌ها.
        /// </summary>
        public static string BlazorServer_Tablelist {
            get {
                return ResourceManager.GetString("BlazorServer_Tablelist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام جدول: {0}.
        /// </summary>
        public static string BlazorServer_TableName {
            get {
                return ResourceManager.GetString("BlazorServer_TableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تگ.
        /// </summary>
        public static string BlazorServer_Tag {
            get {
                return ResourceManager.GetString("BlazorServer_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسته بندی تگ.
        /// </summary>
        public static string BlazorServer_TagCategory {
            get {
                return ResourceManager.GetString("BlazorServer_TagCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام فرم.
        /// </summary>
        public static string BlazorServer_Task {
            get {
                return ResourceManager.GetString("BlazorServer_Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست ‌تاییدها.
        /// </summary>
        public static string BlazorServer_TasksList {
            get {
                return ResourceManager.GetString("BlazorServer_TasksList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بارگزاری.
        /// </summary>
        public static string BlazorServer_Upload {
            get {
                return ResourceManager.GetString("BlazorServer_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بارگزاری شد.
        /// </summary>
        public static string BlazorServer_Uploaded {
            get {
                return ResourceManager.GetString("BlazorServer_Uploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربرانی که در موقعیت {0} هستند.
        /// </summary>
        public static string BlazorServer_UsersInLocation {
            get {
                return ResourceManager.GetString("BlazorServer_UsersInLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربرانی که در سمت {0} هستند.
        /// </summary>
        public static string BlazorServer_UsersInPosition {
            get {
                return ResourceManager.GetString("BlazorServer_UsersInPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متغییر.
        /// </summary>
        public static string BlazorServer_Variable {
            get {
                return ResourceManager.GetString("BlazorServer_Variable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هشدار.
        /// </summary>
        public static string BlazorServer_Warning {
            get {
                return ResourceManager.GetString("BlazorServer_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} خوش آمدید.
        /// </summary>
        public static string BlazorServer_Welcome {
            get {
                return ResourceManager.GetString("BlazorServer_Welcome", resourceCulture);
            }
        }
    }
}
