global using Ardalis.Result;
global using Ardalis.SharedKernel;
global using Grpc.Core;
global using Grpc.Core.Interceptors;
global using MediatR;
global using Microsoft.AspNetCore.Server.Kestrel.Core;
global using Newtonsoft.Json;
global using Serilog;
global using Serilog.Context;
